/**
 * `GET /api/leash/models` — the merged model inventory (catalog + config + disk + live).
 * `?catalog=1` includes the full SDK catalog (for the download picker). If the catalog
 * dump is missing it is regenerated by SPAWNING the tsx child (`leash-model-catalog.mts`)
 * — the SDK never loads inside the Next process.
 */
import { existsSync } from "node:fs";
import { modelsInventory, catalogWithFit, CATALOG_FILE } from "../../../../lib/leash/models.ts";
import { invalidateJsonCache } from "../../../../lib/leash/json-store.ts";
import { spawnHelperScript } from "../../../../lib/leash/runtime.ts";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** Regenerate the catalog dump in a child process (~2s; SDK constants only, no model I/O). Runs via the
 *  bundled qvac runtime in the packaged app (no system node/npx is present) — see lib/leash/runtime.ts. */
function regenCatalog(): Promise<boolean> {
  return new Promise((resolve) => {
    const child = spawnHelperScript("leash-model-catalog.mts");
    child.on("exit", (code) => {
      invalidateJsonCache(CATALOG_FILE);
      resolve(code === 0);
    });
    child.on("error", () => resolve(false));
  });
}

export async function GET(req: Request): Promise<Response> {
  const url = new URL(req.url);
  if (!existsSync(CATALOG_FILE) || url.searchParams.get("refreshCatalog") === "1") {
    await regenCatalog();
  }
  const inventory = await modelsInventory();
  if (url.searchParams.get("catalog") === "1") {
    return Response.json({ ...inventory, catalog: await catalogWithFit() });
  }
  return Response.json(inventory);
}
