/**
 * `GET /api/leash/models` — the merged model inventory (catalog + config + disk + live).
 * `?catalog=1` includes the full SDK catalog (for the download picker). If the catalog
 * dump is missing it is regenerated by SPAWNING the tsx child (`leash-model-catalog.mts`)
 * — the SDK never loads inside the Next process.
 */
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { modelsInventory, catalogWithFit, CATALOG_FILE } from "../../../../lib/leash/models.ts";
import { DATA_DIR, invalidateJsonCache } from "../../../../lib/leash/json-store.ts";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** repo root (data/..) — cwd for spawned children so npx/tsx resolve from the workspace. */
const ROOT = join(DATA_DIR, "..");
const CATALOG_SCRIPT = join(ROOT, "apps", "web", "scripts", "leash-model-catalog.mts");

/** Regenerate the catalog dump in a child process (~2s; SDK constants only, no model I/O). */
function regenCatalog(): Promise<boolean> {
  return new Promise((resolve) => {
    const child = spawn("npx", ["tsx", CATALOG_SCRIPT], { cwd: ROOT, stdio: "ignore" });
    child.on("exit", (code) => {
      invalidateJsonCache(CATALOG_FILE);
      resolve(code === 0);
    });
    child.on("error", () => resolve(false));
  });
}

export async function GET(req: Request): Promise<Response> {
  const url = new URL(req.url);
  if (!existsSync(CATALOG_FILE) || url.searchParams.get("refreshCatalog") === "1") {
    await regenCatalog();
  }
  const inventory = await modelsInventory();
  if (url.searchParams.get("catalog") === "1") {
    return Response.json({ ...inventory, catalog: await catalogWithFit() });
  }
  return Response.json(inventory);
}
