import type { CapabilityAgent, CapabilitySkill } from "../../../../packages/capability-runtime/src/index";

const SOURCE = "local" as const;

export const MOBILE_BUILTIN_SKILLS: CapabilitySkill[] = [
  {
    slug: "task-manager",
    name: "task-manager",
    description: "Manage the user's todo list with the on-device task tools.",
    enabled: true,
    body:
      [
        "Use the task list as the shared source of truth.",
        "List related tasks before creating a duplicate.",
        "Create a task when the user expresses a commitment, and update or complete it when they say progress changed.",
      ].join("\n"),
    tools: ["list_tasks", "add_task", "complete_task", "delete_task"],
    steps: [],
    examples: ["what is on my list", "add a task to renew the domain", "mark the domain task done"],
    whenToUse: "tasks, todos, reminders, task list",
    builtin: true,
    userInvocable: true,
    disableModelInvocation: false,
    files: [],
    extras: {},
    source: SOURCE,
    pluginId: "",
  },
  {
    slug: "memory-keeper",
    name: "memory-keeper",
    description: "Store and recall durable user facts and preferences on this device.",
    enabled: true,
    body:
      [
        "Use long-term memory for stable user facts and preferences.",
        "Recall stored memories before answering questions about the user's preferences or personal context.",
        "Remember only durable information the user asked to keep or clearly stated about themselves.",
      ].join("\n"),
    tools: ["list_memories", "remember"],
    steps: [],
    examples: ["remember that I prefer concise answers", "what do you know about me"],
    whenToUse: "memory, preferences, facts about the user",
    builtin: true,
    userInvocable: true,
    disableModelInvocation: false,
    files: [],
    extras: {},
    source: SOURCE,
    pluginId: "",
  },
  {
    slug: "health-safety",
    name: "health-safety",
    description: "Handle health and wellbeing questions cautiously with the local note and memory context.",
    enabled: true,
    body:
      [
        "Use educational, non-diagnostic language.",
        "For personal health context, search local notes and memories before answering.",
        "If symptoms sound urgent or dangerous, advise immediate emergency or clinician help before anything else.",
      ].join("\n"),
    tools: ["search_notes", "list_memories", "remember"],
    steps: [],
    examples: ["what do my recent health notes say", "is this symptom serious"],
    whenToUse: "health, symptoms, medication, wellbeing",
    builtin: true,
    userInvocable: true,
    disableModelInvocation: false,
    files: [],
    extras: {},
    source: SOURCE,
    pluginId: "",
  },
];

export const MOBILE_BUILTIN_AGENTS: CapabilityAgent[] = [
  {
    slug: "leash",
    source: SOURCE,
    pluginId: "",
    name: "Leash",
    description: "The default on-device assistant.",
    body: "",
    model: "",
    tools: [],
    disallowedTools: [],
    skills: [],
    maxTurns: 6,
    enabled: true,
    builtin: true,
    mcpServers: { refs: [], inline: [] },
    memory: "",
    permissionMode: "",
    hooks: "",
    background: false,
    effort: "",
    isolation: "",
    color: "",
    initialPrompt: "",
  },
  {
    slug: "health",
    source: SOURCE,
    pluginId: "",
    name: "Joy",
    description: "Health and wellbeing specialist for symptoms, medications, and note-grounded guidance.",
    body:
      [
        "Identity: Joy, Leash's health and wellbeing specialist.",
        "Use careful, educational language and say when records or context are incomplete.",
        "Search the user's local notes or memories before answering personal health questions.",
        "If the user describes emergency symptoms, immediate danger, or self-harm risk, tell them to seek urgent help now.",
      ].join("\n"),
    model: "",
    tools: ["search_notes", "list_memories", "remember"],
    disallowedTools: [],
    skills: ["health-safety", "memory-keeper"],
    maxTurns: 6,
    enabled: true,
    builtin: true,
    mcpServers: { refs: [], inline: [] },
    memory: "",
    permissionMode: "",
    hooks: "",
    background: false,
    effort: "",
    isolation: "",
    color: "",
    initialPrompt: "",
  },
  {
    slug: "researcher",
    source: SOURCE,
    pluginId: "",
    name: "Ruth",
    description: "Research specialist for deeper investigations, especially when MCP search tools are available.",
    body:
      [
        "Identity: Ruth, Leash's research specialist.",
        "Prefer source-backed answers and clearly separate confirmed facts from uncertainty.",
        "If the runtime has search tools, use them before answering current or comparative questions.",
      ].join("\n"),
    model: "",
    tools: [],
    disallowedTools: [],
    skills: [],
    maxTurns: 8,
    enabled: true,
    builtin: true,
    mcpServers: { refs: [], inline: [] },
    memory: "",
    permissionMode: "",
    hooks: "",
    background: false,
    effort: "",
    isolation: "",
    color: "",
    initialPrompt: "",
  },
  {
    slug: "summarizer",
    source: SOURCE,
    pluginId: "",
    name: "Bree",
    description: "Summarize long notes, chats, and documents into concise takeaways.",
    body:
      [
        "Identity: Bree, Leash's summarization specialist.",
        "Preserve key facts, decisions, dates, and action items while compressing repetition.",
        "Use the available local context tools before summarizing personal notes or stored context.",
      ].join("\n"),
    model: "",
    tools: ["search_notes", "list_memories", "list_tasks"],
    disallowedTools: [],
    skills: [],
    maxTurns: 4,
    enabled: true,
    builtin: true,
    mcpServers: { refs: [], inline: [] },
    memory: "",
    permissionMode: "",
    hooks: "",
    background: false,
    effort: "",
    isolation: "",
    color: "",
    initialPrompt: "",
  },
  {
    slug: "coder",
    source: SOURCE,
    pluginId: "",
    name: "Grace",
    description: "Coding specialist for explaining or drafting code when the code is already in the conversation.",
    body:
      [
        "Identity: Grace, Leash's coding specialist.",
        "Work from code the user pasted or described here; do not invent a local file system you cannot see.",
        "Explain tradeoffs clearly and keep code minimal and coherent.",
      ].join("\n"),
    model: "",
    tools: [],
    disallowedTools: [],
    skills: [],
    maxTurns: 6,
    enabled: true,
    builtin: true,
    mcpServers: { refs: [], inline: [] },
    memory: "",
    permissionMode: "",
    hooks: "",
    background: false,
    effort: "",
    isolation: "",
    color: "",
    initialPrompt: "",
  },
];
